version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
        - POSTGRES_DB=storedb
        - POSTGRES_USER=store
        - POSTGRES_PASSWORD=storepass
    ports:
      - 5433:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@store.com
      - PGADMIN_DEFAULT_PASSWORD=storepass
    ports:
      - 5050:80

  mysql:
    image: mysql:5
    environment:
      - MYSQL_DATABASE=storedb
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=storepass
      - MYSQL_PORT=3306
    ports:
      - 3306:3306
    volumes:
      - ./mydata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=storepass
      - PMA_HOST=mysql
    ports:
      - 8080:80
